# -*- coding: utf-8 -*-
"""ai_agent_math_factorial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J7T_uOw4FsJWyYE3Rda_FlikI1mUSYap
"""

!pip install -U langchain-classic langchain-experimental langchain-huggingface transformers accelerate
!pip install requests==2.32.4

from threading import Thread
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    pipeline as hf_pipeline,
    TextIteratorStreamer,
    StoppingCriteria,
    StoppingCriteriaList,
)
from langchain_classic.agents import AgentExecutor, create_react_agent
from langchain_experimental.tools.python.tool import PythonREPLTool
from langchain_huggingface import HuggingFacePipeline
from langchain_core.prompts import PromptTemplate
from langchain_core.outputs import GenerationChunk


class PatchedHuggingFacePipeline(HuggingFacePipeline):
    def _stream(self, prompt, stop=None, run_manager=None, **kwargs):
        pipeline_kwargs = kwargs.get("pipeline_kwargs", {})
        skip_prompt = kwargs.get("skip_prompt", True)

        stopping_criteria = None
        if stop is not None:
            stop_ids = self.pipeline.tokenizer.convert_tokens_to_ids(stop)
            if not isinstance(stop_ids, list):
                stop_ids = [stop_ids]

            class StopOnTokens(StoppingCriteria):
                def __call__(self, input_ids, scores, **kwargs):
                    return any(
                        stop_id is not None and input_ids[0][-1] == stop_id
                        for stop_id in stop_ids
                    )

            stopping_criteria = StoppingCriteriaList([StopOnTokens()])

        streamer = TextIteratorStreamer(
            self.pipeline.tokenizer,
            timeout=None,  # key fix
            skip_prompt=skip_prompt,
            skip_special_tokens=True,
        )

        generation_kwargs = {
            "text_inputs": prompt,
            "streamer": streamer,
            **pipeline_kwargs,
        }

        if stopping_criteria is not None:
            generation_kwargs["stopping_criteria"] = stopping_criteria

        thread = Thread(target=self.pipeline, kwargs=generation_kwargs)
        thread.start()

        for text in streamer:
            chunk = GenerationChunk(text=text)
            if run_manager:
                run_manager.on_llm_new_token(chunk.text, chunk=chunk)
            yield chunk

model_id = "Qwen/Qwen2.5-1.5B-Instruct"

tokenizer = AutoTokenizer.from_pretrained(model_id)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

model = AutoModelForCausalLM.from_pretrained(
    model_id,
    torch_dtype="auto",
    device_map="auto",
)

pipe = hf_pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    max_new_tokens=128,
    do_sample=False,
    return_full_text=False,
    pad_token_id=tokenizer.eos_token_id,
)

llm = PatchedHuggingFacePipeline(pipeline=pipe)

tools = [PythonREPLTool()]

prompt = PromptTemplate.from_template("""
You are an agent that can use tools.

You have access to the following tools:
{tools}

IMPORTANT RULES:
- Output exactly ONE of these at a time:
  1. either an Action + Action Input
  2. or a Final Answer
- Do NOT output Observation yourself.
- Do NOT output Final Answer in the same response as an Action.
- If you choose an Action, stop immediately after Action Input.

Use exactly this format:

Question: the question to answer
Thought: your reasoning about what to do next
Action: one of [{tool_names}]
Action Input: the input to the action

OR, if you already know the answer:

Question: the question to answer
Thought: your reasoning about what to do next
Final Answer: the answer

Question: {input}
Thought: {agent_scratchpad}
""")

agent = create_react_agent(
    llm=llm,
    tools=tools,
    prompt=prompt,
    stop_sequence=False,
)

agent_executor = AgentExecutor(
    agent=agent,
    tools=tools,
    verbose=True,
    handle_parsing_errors=True,
    max_iterations=8,
)

result = agent_executor.invoke(
    {"input": "Use Python to calculate factorial of 6"}
    #{"input": "Use Python to calculate sum of odd numbers between 1 to 20"}
    #{"input": "Use Python to calculate sum of even numbers between 1 to 10"}
    #{"input": "Use Python to calculate sum of numbers from 1 to 10"}
)

print(result["output"])

